version: "3.7"

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: testownik
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1211
            PGDATA: /data/postgres
        volumes:
            - postgres-data:/data/postgres
        ports:
            - "5432:5432"
volumes: 
    postgres-data:

